/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author ASUS
 */
import backend.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class FrmPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form FrmBuku
     */
    public FrmPeminjaman() {
        initComponents();
        activateAllField();
        disableBtnUpdate();
        tampilkanData();
        kosongkanForm();

        // Set tanggal pinjam secara otomatis ke hari ini
        setTanggalPinjamHariIni();
    }

    private void setTanggalPinjamHariIni() {
        Date today = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txtTglPinjam.setText(sdf.format(today));
        txtTglKembali.setText(""); // Kosongkan untuk tanggal kembali
    }

    private void setTanggalKembaliHariIni() {
        Date today = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txtTglKembali.setText(sdf.format(today));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdPinjam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdPegawai = new javax.swing.JTextField();
        namaPegawai = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdAnggota = new javax.swing.JTextField();
        namaAnggota = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdBuku = new javax.swing.JTextField();
        judulBuku = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btncariPegawai = new javax.swing.JButton();
        btncariAnggota = new javax.swing.JButton();
        btncariBuku = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPeminjaman = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        txtTglKembali = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("FORM PEMINJAMAN");

        jLabel2.setText("ID Peminjaman");

        txtIdPinjam.setEnabled(false);
        txtIdPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPinjamActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Pegawai");

        jLabel4.setText("ID Anggota");

        jLabel5.setText("ID Buku");

        txtIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBukuActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Pinjam");

        jLabel7.setText("Tanggal Kembali");

        btncariPegawai.setText("Cari");
        btncariPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariPegawaiActionPerformed(evt);
            }
        });

        btncariAnggota.setText("Cari");
        btncariAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariAnggotaActionPerformed(evt);
            }
        });

        btncariBuku.setText("Cari");
        btncariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariBukuActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah Baru");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPeminjaman);

        jLabel8.setText("yyyy-mm-dd");

        jLabel9.setText("yyyy-mm-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIdPinjam)
                                            .addComponent(txtIdPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btncariPegawai))
                                    .addComponent(namaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(judulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTglPinjam)
                                            .addComponent(txtTglKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtIdBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                            .addComponent(txtIdAnggota, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btncariAnggota)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(namaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btncariBuku)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncariPegawai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPegawai)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncariAnggota))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btncariBuku))))
                    .addComponent(namaAnggota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulBuku)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnUpdate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBukuActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPeminjaman.getModel();
        int row = tblPeminjaman.getSelectedRow();

        Peminjaman pinjam = new Peminjaman().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        pinjam.delete();
        activateAllField();
        disableBtnUpdate();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        activateAllField();
        disableBtnUpdate();
        kosongkanForm();
        setTanggalPinjamHariIni();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtIdPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPinjamActionPerformed

    private void btncariPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariPegawaiActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil teks dari TextField dan hapus spasi tambahan
            String input = txtIdPegawai.getText().trim();

            // Cek apakah input kosong
            if (input.isEmpty()) {
                namaPegawai.setText("Input tidak boleh kosong");
                return;
            }

            // Validasi input: coba konversi input ke angka
            int keyword = Integer.parseInt(input);

            // Panggil metode getById untuk mencari anggota berdasarkan ID
            Pegawai hasil = new Pegawai().getById(keyword);

            // Cek apakah hasil pencarian kosong
            if (hasil != null && hasil.getNama() != null) {
                // Tampilkan hanya nama anggota
                namaPegawai.setText("Nama: " + hasil.getNama());
            } else {
                namaPegawai.setText("Pegawai tidak ditemukan.");
            }
        } catch (NumberFormatException e) {
            // Tampilkan pesan jika input bukan angka
            namaPegawai.setText("Input harus berupa angka.");
        } catch (Exception e) {
            // Tangkap exception lain jika ada kesalahan
            namaPegawai.setText("Terjadi kesalahan");
            e.printStackTrace(); // Log error untuk debugging
        }
    }//GEN-LAST:event_btncariPegawaiActionPerformed

    private void btncariAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariAnggotaActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil teks dari TextField dan hapus spasi tambahan
            String input = txtIdAnggota.getText().trim();

            // Cek apakah input kosong
            if (input.isEmpty()) {
                namaAnggota.setText("Input tidak boleh kosong.");
                return;
            }

            // Validasi input: coba konversi input ke angka
            int keyword = Integer.parseInt(input);

            // Panggil metode getById untuk mencari anggota berdasarkan ID
            Anggota hasil = new Anggota().getById(keyword);

            // Cek apakah hasil pencarian kosong
            if (hasil != null && hasil.getNama() != null) {
                // Tampilkan hanya nama anggota
                namaAnggota.setText("Nama: " + hasil.getNama());
            } else {
                namaAnggota.setText("Anggota tidak ditemukan.");
            }
        } catch (NumberFormatException e) {
            // Tampilkan pesan jika input bukan angka
            namaAnggota.setText("Input harus angka.");
        } catch (Exception e) {
            // Tangkap exception lain jika ada kesalahan
            namaAnggota.setText("Terjadi kesalahan.");
            e.printStackTrace(); // Log error untuk debugging
        }
    }//GEN-LAST:event_btncariAnggotaActionPerformed

    private void btncariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariBukuActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil teks dari TextField dan hapus spasi tambahan
            String input = txtIdBuku.getText().trim();

            // Cek apakah input kosong
            if (input.isEmpty()) {
                judulBuku.setText("Input tidak boleh kosong");
                return;
            }

            // Validasi input: coba konversi input ke angka
            int keyword = Integer.parseInt(input);

            // Panggil metode getById untuk mencari anggota berdasarkan ID
            Buku hasil = new Buku().getById(keyword);

            // Cek apakah hasil pencarian kosong
            if (hasil != null && hasil.getJudul() != null) {
                // Tampilkan hanya nama anggota
                judulBuku.setText("Nama: " + hasil.getJudul());
            } else {
                judulBuku.setText("Buku tidak ditemukan.");
            }
        } catch (NumberFormatException e) {
            // Tampilkan pesan jika input bukan angka
            judulBuku.setText("Input harus angka.");
        } catch (Exception e) {
            // Tangkap exception lain jika ada kesalahan
            judulBuku.setText("Terjadi kesalahan");
            e.printStackTrace(); // Log error untuk debugging
        }
    }//GEN-LAST:event_btncariBukuActionPerformed

    private void tblPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeminjamanMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblPeminjaman.getModel();
        int selectedRow = tblPeminjaman.getSelectedRow();
        Peminjaman pin = new Peminjaman();

        pin = pin.getById(Integer.parseInt(model.getValueAt(selectedRow, 0).toString()));

        txtIdPinjam.setText(String.valueOf(pin.getIdpeminjaman()));
        txtIdPegawai.setText(String.valueOf(pin.getPegawai().getIdpegawai()));
        txtIdAnggota.setText(String.valueOf(pin.getAnggota().getIdanggota()));
        txtIdBuku.setText(String.valueOf(pin.getBuku().getIdbuku()));

        txtTglPinjam.setText(pin.getTglpinjam());
        if (txtTglKembali.getText().isEmpty()) {
            setTanggalKembaliHariIni();
        } else {
            txtTglKembali.setText(pin.getTglkembali());
        }

        disableAllFieldsExceptTglKembali();
        enableBtnUpdate();
    }//GEN-LAST:event_tblPeminjamanMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // Validasi input field
        if (txtIdPegawai.getText().isEmpty() || txtIdAnggota.getText().isEmpty() || txtIdBuku.getText().isEmpty() || txtTglPinjam.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Peminjaman pinjam = new Peminjaman();
            pinjam.setIdpeminjaman(Integer.parseInt(txtIdPinjam.getText()));
            pinjam.getPegawai().setIdpegawai(Integer.parseInt(txtIdPegawai.getText()));
            pinjam.getAnggota().setIdanggota(Integer.parseInt(txtIdAnggota.getText()));
            pinjam.getBuku().setIdbuku(Integer.parseInt(txtIdBuku.getText()));

            pinjam.setTglpinjam(txtTglPinjam.getText());
            pinjam.setTglkembali(txtTglKembali.getText());

            pinjam.save();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            kosongkanForm();
            tampilkanData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // Validasi input field
        if (txtIdPegawai.getText().isEmpty() || txtIdAnggota.getText().isEmpty() || txtIdBuku.getText().isEmpty() || txtTglPinjam.getText().isEmpty() || txtTglKembali.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Gagal", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Peminjaman pinjam = new Peminjaman();
            pinjam.setIdpeminjaman(Integer.parseInt(txtIdPinjam.getText()));
            pinjam.getPegawai().setIdpegawai(Integer.parseInt(txtIdPegawai.getText()));
            pinjam.getAnggota().setIdanggota(Integer.parseInt(txtIdAnggota.getText()));
            pinjam.getBuku().setIdbuku(Integer.parseInt(txtIdBuku.getText()));

            pinjam.setTglpinjam(txtTglPinjam.getText());
            pinjam.setTglkembali(txtTglKembali.getText());

            pinjam.save();

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            kosongkanForm();
            tampilkanData();
            activateAllField();
            disableBtnUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPeminjaman().setVisible(true);
            }
        });
    }

    private void activateAllField() {
        txtIdPegawai.setEnabled(true);
        txtIdAnggota.setEnabled(true);
        txtIdBuku.setEnabled(true);
        txtTglPinjam.setEnabled(true);
        txtTglKembali.setEnabled(false);
    }

    private void disableAllFieldsExceptTglKembali() {
        txtIdPegawai.setEnabled(false);
        txtIdAnggota.setEnabled(false);
        txtIdBuku.setEnabled(false);
        txtTglPinjam.setEnabled(false);
        txtTglKembali.setEnabled(true);
    }

    private void disableBtnUpdate() {
        btnSimpan.setEnabled(true);
        btnUpdate.setEnabled(false);
    }

    private void enableBtnUpdate() {
        btnSimpan.setEnabled(false);
        btnUpdate.setEnabled(true);
    }

    public void kosongkanForm() {
        txtIdPinjam.setText("0");
        txtIdPegawai.setText("");
        txtIdAnggota.setText("");
        txtIdBuku.setText("");
        setTanggalPinjamHariIni();
        txtTglKembali.setText("");

        // Kosongkan label tambahan
        namaPegawai.setText("");
        namaAnggota.setText("");
        judulBuku.setText("");
    }

    public void tampilkanData() {
        String[] kolom = {"ID", "Pegawai", "Anggota", "Buku", "Tanggal Pinjam", "Tanggal Kembali"};
        ArrayList<Peminjaman> list = new Peminjaman().getAll();
        Object rowData[] = new Object[6];

        tblPeminjaman.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (Peminjaman p : list) {
            rowData[0] = p.getIdpeminjaman();
            rowData[1] = p.getPegawai().getNama();
            rowData[2] = p.getAnggota().getNama();
            rowData[3] = p.getBuku().getJudul();
            rowData[4] = p.getTglpinjam();
            rowData[5] = p.getTglkembali();

            ((DefaultTableModel) tblPeminjaman.getModel()).addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btncariAnggota;
    private javax.swing.JButton btncariBuku;
    private javax.swing.JButton btncariPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judulBuku;
    private javax.swing.JLabel namaAnggota;
    private javax.swing.JLabel namaPegawai;
    private javax.swing.JTable tblPeminjaman;
    private javax.swing.JTextField txtIdAnggota;
    private javax.swing.JTextField txtIdBuku;
    private javax.swing.JTextField txtIdPegawai;
    private javax.swing.JTextField txtIdPinjam;
    private javax.swing.JTextField txtTglKembali;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables
}
